### ISSUE TITLE
Fix VM name to hostname conversion

### ISSUE THREAD

**Issue by WilliamOConnell** [tjcsl/director#14]
Currently, the name of a VM has to be unique, but it can contain spaces. These spaces are changed to dashes to form the subdomain for the hostname of the VM. This means that if you create two VMs, one called "test vm" and one called "test-vm", they will both show as having the same host name: "test-vm.vm.sites.tjhsst.edu".

**Comment by ezwang** [comment]
There is also a problem with uppercase and lowercase letters. Both "Testing" and "testing" both show the same hostname: "testing.vm.sites.tjhsst.edu".
