### ISSUE TITLE
Expand and Organize Documentation

### ISSUE THREAD

**Issue by naitian** [tjcsl/director#31]
Have multiple pages for documentation, and include documentation beyond just Director functionalities (something similar to Digital Ocean docs).

**Comment by ezwang** [comment]
This is similar to issue #9.

**Comment by naitian** [comment]
New documentation system resolved by 9b0f980aa83c7a51e1a1aeb94e3a00cc3ecbf5e9 - eb00c94c33b4755c9623577d79ee56ff78eef060, so I'll close this issue, but I'll leave #9 open.
