### ISSUE TITLE
Online Terminal not working (WebSocket connection failed)

### ISSUE THREAD

**Issue by liamrathke** [tjcsl/director#47]
I'm trying to use the online terminal to run a project I have for my Android class.
The online terminal appears to be down at the time, I can't type in the field at all. It's just a black field.

<img width="517" alt="screen shot 2018-06-04 at 2 32 40 pm" src="https://user-images.githubusercontent.com/33555592/40934884-401a39b6-6804-11e8-886c-c7404cabab9d.png">

Through Inspect Element, it seems that the issue is related to Director's WebSocket connection.

`WebSocket connection to 'wss://director.tjhsst.edu/ws/' failed: Error during WebSocket handshake: Unexpected response code: 502
addFileListener @ editor.js:1655
d @ raven.js:379
14:31:10.691 `

**Comment by naitian** [comment]
Fixed.

**Comment by liamrathke** [comment]
Wow that was fast, thanks so much @naitian!
